// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notificationtype int32

const (
	Notificationtype_unknown Notificationtype = 0
	Notificationtype_email   Notificationtype = 1
	Notificationtype_sms     Notificationtype = 2
	Notificationtype_push    Notificationtype = 3
)

// Enum value maps for Notificationtype.
var (
	Notificationtype_name = map[int32]string{
		0: "unknown",
		1: "email",
		2: "sms",
		3: "push",
	}
	Notificationtype_value = map[string]int32{
		"unknown": 0,
		"email":   1,
		"sms":     2,
		"push":    3,
	}
)

func (x Notificationtype) Enum() *Notificationtype {
	p := new(Notificationtype)
	*p = x
	return p
}

func (x Notificationtype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Notificationtype) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_proto_enumTypes[0].Descriptor()
}

func (Notificationtype) Type() protoreflect.EnumType {
	return &file_proto_notification_proto_enumTypes[0]
}

func (x Notificationtype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Notificationtype.Descriptor instead.
func (Notificationtype) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

type HealthcheckresponseCheckhealthstatuses int32

const (
	Healthcheckresponse_unknown    HealthcheckresponseCheckhealthstatuses = 0
	Healthcheckresponse_serving    HealthcheckresponseCheckhealthstatuses = 1
	Healthcheckresponse_notserving HealthcheckresponseCheckhealthstatuses = 2
)

// Enum value maps for HealthcheckresponseCheckhealthstatuses.
var (
	HealthcheckresponseCheckhealthstatuses_name = map[int32]string{
		0: "unknown",
		1: "serving",
		2: "notserving",
	}
	HealthcheckresponseCheckhealthstatuses_value = map[string]int32{
		"unknown":    0,
		"serving":    1,
		"notserving": 2,
	}
)

func (x HealthcheckresponseCheckhealthstatuses) Enum() *HealthcheckresponseCheckhealthstatuses {
	p := new(HealthcheckresponseCheckhealthstatuses)
	*p = x
	return p
}

func (x HealthcheckresponseCheckhealthstatuses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthcheckresponseCheckhealthstatuses) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_proto_enumTypes[1].Descriptor()
}

func (HealthcheckresponseCheckhealthstatuses) Type() protoreflect.EnumType {
	return &file_proto_notification_proto_enumTypes[1]
}

func (x HealthcheckresponseCheckhealthstatuses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthcheckresponseCheckhealthstatuses.Descriptor instead.
func (HealthcheckresponseCheckhealthstatuses) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{5, 0}
}

// defining the variables
type Notificationrequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// todo : read the protobuf docs  these nums 1 - 15 for binary conversion something
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          Notificationtype       `protobuf:"varint,5,opt,name=type,proto3,enum=notificitationservice.Notificationtype" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notificationrequest) Reset() {
	*x = Notificationrequest{}
	mi := &file_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notificationrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notificationrequest) ProtoMessage() {}

func (x *Notificationrequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notificationrequest.ProtoReflect.Descriptor instead.
func (*Notificationrequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notificationrequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notificationrequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Notificationrequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notificationrequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Notificationrequest) GetType() Notificationtype {
	if x != nil {
		return x.Type
	}
	return Notificationtype_unknown
}

type Notificationresponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NotificationId string                 `protobuf:"bytes,3,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notificationresponse) Reset() {
	*x = Notificationresponse{}
	mi := &file_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notificationresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notificationresponse) ProtoMessage() {}

func (x *Notificationresponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notificationresponse.ProtoReflect.Descriptor instead.
func (*Notificationresponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Notificationresponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Notificationresponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notificationresponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type Batchnotificationresponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalSent              int32                  `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	Success                int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Failed                 int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	FailedUserEmails       []string               `protobuf:"bytes,4,rep,name=failed_user_emails,json=failedUserEmails,proto3" json:"failed_user_emails,omitempty"`
	FailedUserPhoneNumbers []string               `protobuf:"bytes,5,rep,name=failed_user_phone_numbers,json=failedUserPhoneNumbers,proto3" json:"failed_user_phone_numbers,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Batchnotificationresponse) Reset() {
	*x = Batchnotificationresponse{}
	mi := &file_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batchnotificationresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batchnotificationresponse) ProtoMessage() {}

func (x *Batchnotificationresponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batchnotificationresponse.ProtoReflect.Descriptor instead.
func (*Batchnotificationresponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *Batchnotificationresponse) GetTotalSent() int32 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *Batchnotificationresponse) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *Batchnotificationresponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *Batchnotificationresponse) GetFailedUserEmails() []string {
	if x != nil {
		return x.FailedUserEmails
	}
	return nil
}

func (x *Batchnotificationresponse) GetFailedUserPhoneNumbers() []string {
	if x != nil {
		return x.FailedUserPhoneNumbers
	}
	return nil
}

type Newbatchnotificationresponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalSent        int32                  `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	Success          int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Failed           int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	FailedUserEmails []string               `protobuf:"bytes,4,rep,name=failed_user_emails,json=failedUserEmails,proto3" json:"failed_user_emails,omitempty"`
	FailedPhoneNums  []string               `protobuf:"bytes,5,rep,name=failed_phone_nums,json=failedPhoneNums,proto3" json:"failed_phone_nums,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Newbatchnotificationresponse) Reset() {
	*x = Newbatchnotificationresponse{}
	mi := &file_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Newbatchnotificationresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Newbatchnotificationresponse) ProtoMessage() {}

func (x *Newbatchnotificationresponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Newbatchnotificationresponse.ProtoReflect.Descriptor instead.
func (*Newbatchnotificationresponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *Newbatchnotificationresponse) GetTotalSent() int32 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *Newbatchnotificationresponse) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *Newbatchnotificationresponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *Newbatchnotificationresponse) GetFailedUserEmails() []string {
	if x != nil {
		return x.FailedUserEmails
	}
	return nil
}

func (x *Newbatchnotificationresponse) GetFailedPhoneNums() []string {
	if x != nil {
		return x.FailedPhoneNums
	}
	return nil
}

type Healthcheckrequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serivice      string                 `protobuf:"bytes,1,opt,name=serivice,proto3" json:"serivice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Healthcheckrequest) Reset() {
	*x = Healthcheckrequest{}
	mi := &file_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Healthcheckrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Healthcheckrequest) ProtoMessage() {}

func (x *Healthcheckrequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Healthcheckrequest.ProtoReflect.Descriptor instead.
func (*Healthcheckrequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *Healthcheckrequest) GetSerivice() string {
	if x != nil {
		return x.Serivice
	}
	return ""
}

type Healthcheckresponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Status        HealthcheckresponseCheckhealthstatuses `protobuf:"varint,1,opt,name=status,proto3,enum=notificitationservice.HealthcheckresponseCheckhealthstatuses" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Healthcheckresponse) Reset() {
	*x = Healthcheckresponse{}
	mi := &file_proto_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Healthcheckresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Healthcheckresponse) ProtoMessage() {}

func (x *Healthcheckresponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Healthcheckresponse.ProtoReflect.Descriptor instead.
func (*Healthcheckresponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{5}
}

func (x *Healthcheckresponse) GetStatus() HealthcheckresponseCheckhealthstatuses {
	if x != nil {
		return x.Status
	}
	return Healthcheckresponse_unknown
}

type Notificationrequestwithdata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserEmail       string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserPhoneNumber string                 `protobuf:"bytes,2,opt,name=user_phone_number,json=userPhoneNumber,proto3" json:"user_phone_number,omitempty"`
	ReportType      string                 `protobuf:"bytes,3,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	ReportLocation  string                 `protobuf:"bytes,4,opt,name=report_location,json=reportLocation,proto3" json:"report_location,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type            Notificationtype       `protobuf:"varint,6,opt,name=type,proto3,enum=notificitationservice.Notificationtype" json:"type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Notificationrequestwithdata) Reset() {
	*x = Notificationrequestwithdata{}
	mi := &file_proto_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notificationrequestwithdata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notificationrequestwithdata) ProtoMessage() {}

func (x *Notificationrequestwithdata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notificationrequestwithdata.ProtoReflect.Descriptor instead.
func (*Notificationrequestwithdata) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{6}
}

func (x *Notificationrequestwithdata) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *Notificationrequestwithdata) GetUserPhoneNumber() string {
	if x != nil {
		return x.UserPhoneNumber
	}
	return ""
}

func (x *Notificationrequestwithdata) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *Notificationrequestwithdata) GetReportLocation() string {
	if x != nil {
		return x.ReportLocation
	}
	return ""
}

func (x *Notificationrequestwithdata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Notificationrequestwithdata) GetType() Notificationtype {
	if x != nil {
		return x.Type
	}
	return Notificationtype_unknown
}

var File_proto_notification_proto protoreflect.FileDescriptor

const file_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x18proto/notification.proto\x12\x15notificitationservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n" +
	"\x13notificationrequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12;\n" +
	"\x04type\x18\x05 \x01(\x0e2'.notificitationservice.notificationtypeR\x04type\"s\n" +
	"\x14notificationresponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fnotification_id\x18\x03 \x01(\tR\x0enotificationId\"\xd5\x01\n" +
	"\x19batchnotificationresponse\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x01 \x01(\x05R\ttotalSent\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12,\n" +
	"\x12failed_user_emails\x18\x04 \x03(\tR\x10failedUserEmails\x129\n" +
	"\x19failed_user_phone_numbers\x18\x05 \x03(\tR\x16failedUserPhoneNumbers\"\xc9\x01\n" +
	"\x1cnewbatchnotificationresponse\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x01 \x01(\x05R\ttotalSent\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12,\n" +
	"\x12failed_user_emails\x18\x04 \x03(\tR\x10failedUserEmails\x12*\n" +
	"\x11failed_phone_nums\x18\x05 \x03(\tR\x0ffailedPhoneNums\"0\n" +
	"\x12healthcheckrequest\x12\x1a\n" +
	"\bserivice\x18\x01 \x01(\tR\bserivice\"\xae\x01\n" +
	"\x13healthcheckresponse\x12V\n" +
	"\x06status\x18\x01 \x01(\x0e2>.notificitationservice.healthcheckresponse.checkhealthstatusesR\x06status\"?\n" +
	"\x13checkhealthstatuses\x12\v\n" +
	"\aunknown\x10\x00\x12\v\n" +
	"\aserving\x10\x01\x12\x0e\n" +
	"\n" +
	"notserving\x10\x02\"\xa9\x02\n" +
	"\x1bnotificationrequestwithdata\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\x12*\n" +
	"\x11user_phone_number\x18\x02 \x01(\tR\x0fuserPhoneNumber\x12\x1f\n" +
	"\vreport_type\x18\x03 \x01(\tR\n" +
	"reportType\x12'\n" +
	"\x0freport_location\x18\x04 \x01(\tR\x0ereportLocation\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12;\n" +
	"\x04type\x18\x06 \x01(\x0e2'.notificitationservice.notificationtypeR\x04type*=\n" +
	"\x10notificationtype\x12\v\n" +
	"\aunknown\x10\x00\x12\t\n" +
	"\x05email\x10\x01\x12\a\n" +
	"\x03sms\x10\x02\x12\b\n" +
	"\x04push\x10\x032\xfa\x03\n" +
	"\x13notificationservice\x12k\n" +
	"\x10sendnotification\x12*.notificitationservice.notificationrequest\x1a+.notificitationservice.notificationresponse\x12w\n" +
	"\x15sendbatchnotification\x12*.notificitationservice.notificationrequest\x1a0.notificitationservice.batchnotificationresponse(\x01\x12d\n" +
	"\vhealthcheck\x12).notificitationservice.healthcheckrequest\x1a*.notificitationservice.healthcheckresponse\x12\x96\x01\n" +
	")sendnotiificationacceptingdisasterapidata\x122.notificitationservice.notificationrequestwithdata\x1a3.notificitationservice.newbatchnotificationresponse(\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_notification_proto_rawDescOnce sync.Once
	file_proto_notification_proto_rawDescData []byte
)

func file_proto_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)))
	})
	return file_proto_notification_proto_rawDescData
}

var file_proto_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_notification_proto_goTypes = []any{
	(Notificationtype)(0),                       // 0: notificitationservice.notificationtype
	(HealthcheckresponseCheckhealthstatuses)(0), // 1: notificitationservice.healthcheckresponse.checkhealthstatuses
	(*Notificationrequest)(nil),                 // 2: notificitationservice.notificationrequest
	(*Notificationresponse)(nil),                // 3: notificitationservice.notificationresponse
	(*Batchnotificationresponse)(nil),           // 4: notificitationservice.batchnotificationresponse
	(*Newbatchnotificationresponse)(nil),        // 5: notificitationservice.newbatchnotificationresponse
	(*Healthcheckrequest)(nil),                  // 6: notificitationservice.healthcheckrequest
	(*Healthcheckresponse)(nil),                 // 7: notificitationservice.healthcheckresponse
	(*Notificationrequestwithdata)(nil),         // 8: notificitationservice.notificationrequestwithdata
	(*timestamppb.Timestamp)(nil),               // 9: google.protobuf.Timestamp
}
var file_proto_notification_proto_depIdxs = []int32{
	9, // 0: notificitationservice.notificationrequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: notificitationservice.notificationrequest.type:type_name -> notificitationservice.notificationtype
	1, // 2: notificitationservice.healthcheckresponse.status:type_name -> notificitationservice.healthcheckresponse.checkhealthstatuses
	9, // 3: notificitationservice.notificationrequestwithdata.timestamp:type_name -> google.protobuf.Timestamp
	0, // 4: notificitationservice.notificationrequestwithdata.type:type_name -> notificitationservice.notificationtype
	2, // 5: notificitationservice.notificationservice.sendnotification:input_type -> notificitationservice.notificationrequest
	2, // 6: notificitationservice.notificationservice.sendbatchnotification:input_type -> notificitationservice.notificationrequest
	6, // 7: notificitationservice.notificationservice.healthcheck:input_type -> notificitationservice.healthcheckrequest
	8, // 8: notificitationservice.notificationservice.sendnotiificationacceptingdisasterapidata:input_type -> notificitationservice.notificationrequestwithdata
	3, // 9: notificitationservice.notificationservice.sendnotification:output_type -> notificitationservice.notificationresponse
	4, // 10: notificitationservice.notificationservice.sendbatchnotification:output_type -> notificitationservice.batchnotificationresponse
	7, // 11: notificitationservice.notificationservice.healthcheck:output_type -> notificitationservice.healthcheckresponse
	5, // 12: notificitationservice.notificationservice.sendnotiificationacceptingdisasterapidata:output_type -> notificitationservice.newbatchnotificationresponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_notification_proto_init() }
func file_proto_notification_proto_init() {
	if File_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_proto_depIdxs,
		EnumInfos:         file_proto_notification_proto_enumTypes,
		MessageInfos:      file_proto_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_proto = out.File
	file_proto_notification_proto_goTypes = nil
	file_proto_notification_proto_depIdxs = nil
}
